In [1]:
import pandas as pd

In [3]:
df0=pd.DataFrame({
    'name':['nikhil','sairam','charan'],
    'marks':[99,18,45]
})

In [4]:
df0

     name  marks
0  nikhil     99
1  sairam     18
2  charan     45

In [6]:
df=pd.read_csv(r'datasets/health_dataset.csv')

In [7]:
df

    age  gender   bmi     condition
0    58    Male  17.1  Hypertensive
1    33    Male  20.1       Healthy
2    61    Male  31.6       Healthy
3    19    Male  22.1        Anemic
4    56    Male  30.8        Anemic
..  ...     ...   ...           ...
95   74  Female  17.1  Hypertensive
96   68  Female  37.0      Diabetic
97   35    Male  36.6       Healthy
98   42    Male  38.4      Diabetic
99   30  Female  25.4      Diabetic

[100 rows x 4 columns]

In [ ]:
df.head() #Return top 5 rows of a dataset

   age  gender   bmi     condition
0   58    Male  17.1  Hypertensive
1   33    Male  20.1       Healthy
2   61    Male  31.6       Healthy
3   19    Male  22.1        Anemic
4   56    Male  30.8        Anemic
5   44    Male  28.0  Hypertensive
6   69    Male  35.8      Diabetic
7   62  Female  25.2      Diabetic
8   31  Female  19.1         Obese
9   24  Female  38.1        Anemic

In [10]:
df.tail() # return last 5 rows of a dataset

    age  gender   bmi     condition
95   74  Female  17.1  Hypertensive
96   68  Female  37.0      Diabetic
97   35    Male  36.6       Healthy
98   42    Male  38.4      Diabetic
99   30  Female  25.4      Diabetic

In [ ]:
df.shape # Return no of rows and columns

(100, 4)

In [ ]:
df.columns  #Return the column names

Index(['age', 'gender', 'bmi', 'condition'], dtype='object')

In [ ]:
df.dtypes # Return datatype of each columnm

age            int64
gender        object
bmi          float64
condition     object
dtype: object

In [ ]:
df.info() # return No of rows
                #no of columns 
                # non null count
                #  data type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   bmi        100 non-null    float64
 3   condition  100 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 3.3+ KB

In [ ]:
df.describe() # FIVES MEAN 
                #MIN 
                # MAX 
                # PERCENTILE 
                # STD

              age         bmi
count  100.000000  100.000000
mean    45.140000   29.030000
std     18.481779    7.654714
min     18.000000   16.700000
25%     30.750000   21.900000
50%     43.500000   28.550000
75%     61.000000   35.875000
max     75.000000   41.600000

## Data selection

In [ ]:
df['age'] # return only id column data

0     58
1     33
2     61
3     19
4     56
      ..
95    74
96    68
97    35
98    42
99    30
Name: age, Length: 100, dtype: int64

In [22]:
type(df['age'])

pandas.core.series.Series

In [21]:
df[['age','gender','bmi']]

    age  gender   bmi
0    58    Male  17.1
1    33    Male  20.1
2    61    Male  31.6
3    19    Male  22.1
4    56    Male  30.8
..  ...     ...   ...
95   74  Female  17.1
96   68  Female  37.0
97   35    Male  36.6
98   42    Male  38.4
99   30  Female  25.4

[100 rows x 3 columns]

In [23]:
type(df[['age','gender','bmi']])

pandas.core.frame.DataFrame

In [ ]:
df.iloc[1] # return entire row

age              34
gender         Male
bmi            35.1
condition    Anemic
Name: 10, dtype: object

In [ ]:
df.iloc[0, 1]  # Get a Single Value 
                #df.iloc[row_index, column_index]

'Male'

In [31]:
df.iloc[0:3]   # returns multiple rows  
                # start incuded 
                # end excluded

   age gender   bmi     condition
0   58   Male  17.1  Hypertensive
1   33   Male  20.1       Healthy
2   61   Male  31.6       Healthy

In [ ]:
df.iloc[:, 1] # reurtn only single column

0       Male
1       Male
2       Male
3       Male
4       Male
       ...
95    Female
96    Female
97      Male
98      Male
99    Female
Name: gender, Length: 100, dtype: object

In [33]:
df.iloc[:, 0:2]  # return multiple columns

    age  gender
0    58    Male
1    33    Male
2    61    Male
3    19    Male
4    56    Male
..  ...     ...
95   74  Female
96   68  Female
97   35    Male
98   42    Male
99   30  Female

[100 rows x 2 columns]

## Handling NUll values

In [34]:
df1=pd.read_csv(r'datasets/health_dataset_nullvalues.csv')

In [38]:
df1.isnull().sum()

age           8
gender       18
bmi           7
condition    10
dtype: int64

In [ ]:
df1.dropna() # removes rows having null values

     age  gender   bmi     condition
0   58.0    Male  17.1  Hypertensive
2   61.0    Male  31.6       Healthy
3   19.0    Male  22.1        Anemic
4   56.0    Male  30.8        Anemic
6   69.0    Male  35.8      Diabetic
..   ...     ...   ...           ...
92  60.0    Male  25.5        Anemic
95  74.0  Female  17.1  Hypertensive
96  68.0  Female  37.0      Diabetic
98  42.0    Male  38.4      Diabetic
99  30.0  Female  25.4      Diabetic

[65 rows x 4 columns]

In [45]:
df1.fillna(0) # fill null values with 0

     age  gender   bmi     condition
0   58.0    Male  17.1  Hypertensive
1    0.0    Male  20.1       Healthy
2   61.0    Male  31.6       Healthy
3   19.0    Male  22.1        Anemic
4   56.0    Male  30.8        Anemic
..   ...     ...   ...           ...
95  74.0  Female  17.1  Hypertensive
96  68.0  Female  37.0      Diabetic
97  35.0       0  36.6       Healthy
98  42.0    Male  38.4      Diabetic
99  30.0  Female  25.4      Diabetic

[100 rows x 4 columns]

In [46]:
df1.sort_values("age", ascending=False)

     age  gender   bmi     condition
25  75.0     NaN  25.7      Diabetic
91  75.0  Female  21.9      Diabetic
77  74.0     NaN  25.9           NaN
22  74.0     NaN  21.9         Obese
95  74.0  Female  17.1  Hypertensive
..   ...     ...   ...           ...
20   NaN    Male  37.0         Obese
75   NaN    Male  30.2        Anemic
80   NaN    Male  23.2           NaN
89   NaN    Male  27.5       Healthy
93   NaN  Female  41.3           NaN

[100 rows x 4 columns]

In [48]:
df["gender"].value_counts()

gender
Male      53
Female    47
Name: count, dtype: int64

In [49]:
df1.rename(columns={'age':'Age'},inplace=True)

In [50]:
df1.head(2)

    Age gender   bmi     condition
0  58.0   Male  17.1  Hypertensive
1   NaN   Male  20.1       Healthy

In [52]:
df1.fillna(0,inplace=True)

In [53]:
df1['bmi'].astype(int)

0     17
1     20
2     31
3     22
4     30
      ..
95    17
96    37
97    36
98    38
99    25
Name: bmi, Length: 100, dtype: int64

In [56]:
import random

In [58]:
df1['Salary']=[random.randint(10000,100000) for i in range(len(df1))]

In [62]:
df1

     Age  gender   bmi     condition  Salary
0   58.0    Male  17.1  Hypertensive   71846
1    0.0    Male  20.1       Healthy   74046
2   61.0    Male  31.6       Healthy   97404
3   19.0    Male  22.1        Anemic   85594
4   56.0    Male  30.8        Anemic   84764
..   ...     ...   ...           ...     ...
95  74.0  Female  17.1  Hypertensive   87109
96  68.0  Female  37.0      Diabetic   93965
97  35.0       0  36.6       Healthy   70977
98  42.0    Male  38.4      Diabetic   57916
99  30.0  Female  25.4      Diabetic   34470

[100 rows x 5 columns]

In [67]:
def fx(a):
    return a+5000

df1['bonus']=df1['Salary'].apply(fx)

In [76]:
pd.get_dummies(df,columns=['gender','condition'],drop_first=True)

,age,bmi,gender_Male,condition_Diabetic,condition_Healthy,condition_Hypertensive,condition_Obese
0,58,17.1,True,False,False,True,False
1,33,20.1,True,False,True,False,False
2,61,31.6,True,False,True,False,False
3,19,22.1,True,False,False,False,False
4,56,30.8,True,False,False,False,False
...,...,...,...,...,...,...,...
95,74,17.1,False,False,False,True,False
96,68,37.0,False,True,False,False,False
97,35,36.6,True,False,True,False,False
98,42,38.4,True,True,False,False,False
99,30,25.4,False,True,False,False,False