In [17]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv(r'../datasets/Mall_Customers.csv')

In [4]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [5]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='object')

In [6]:
df.dtypes

CustomerID                 int64
Gender                    object
Age                        int64
Annual Income (k$)         int64
Spending Score (1-100)     int64
dtype: object

In [9]:
df['Gender']=pd.get_dummies(df["Gender"],drop_first=True)

In [10]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    True   19                  15                      39
1           2    True   21                  15                      81
2           3   False   20                  16                       6
3           4   False   23                  16                      77
4           5   False   31                  17                      40

In [14]:
df["Gender"]=df["Gender"].map({True:"1",False:"0"})

In [15]:
df.head()

   CustomerID Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1      1   19                  15                      39
1           2      1   21                  15                      81
2           3      0   20                  16                       6
3           4      0   23                  16                      77
4           5      0   31                  17                      40

In [16]:
df.shape

(200, 5)

In [20]:
X=df.drop(columns="Spending Score (1-100)")
y=df['Spending Score (1-100)']

In [18]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

from tensorflow import keras
from tensorflow.keras import layers

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [22]:
scalar=StandardScaler()

In [23]:
x_train_scaled=scalar.fit_transform(X_train)
X_test_scaled=scalar.transform(X_test)

In [ ]:
model=keras.Sequential([
    layers.Input(shape=(x_train_scaled.shape[1],)),
    layers.Dense(32,activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(16,activation='relu'),
    layers.Dropout()
]

)